import React, { useEffect, useRef, useState, useMemo } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TextInput,
  KeyboardAvoidingView, Platform, TouchableOpacity, Pressable,
} from 'react-native';
import { FFButton } from '../components/FFButton';
import { FFPanel } from '../components/FFPanel';
import { CharacterAvatar } from '../components/CharacterAvatar';
import { LifestreamLoader } from '../components/LifestreamLoader';
import { callChatAPI } from '../lib/api';
import { CHAR_COLORS, CHARACTER_IDS, CHAR_NAMES, displayName } from '../lib/characters';
import { safeJsonObject } from '../lib/json';
import { colors } from '../theme/theme';

// ── Helpers ──────────────────────────────────────────────────────────────────

const RELATIONSHIP_CORE_RULES_ZH = [
  '保持角色原作气质，允许现代聊天软件语境。',
  '玩家只能控制自己的话和行动，不能控制其他角色。',
  '主线关系必须只由主线剧情中的选择、对话和事件自然发展。',
];

const CANON_RELATIONSHIPS = {
  'cloud:tifa': {
    zh: 'Cloud 和 Tifa 有童年旧识与复杂信任，熟悉但不应突然过度表白。',
    en: 'Cloud and Tifa share a childhood connection and complicated trust, but avoid sudden over-romantic confession.',
  },
  'cloud:zack': {
    zh: 'Cloud 和 Zack 的关系带有记忆、亏欠与复杂情绪，Cloud 对 Zack 不会轻松得像普通老朋友。',
    en: 'Cloud and Zack have memory, debt, and complicated emotion; Cloud should not treat Zack like a simple casual friend.',
  },
  'zack:aerith': { zh: 'Zack 和 Aerith 有旧日情感，重逢应带有时间和命运的重量。', en: 'Zack and Aerith share old affection; reunion should carry emotional weight.' },
  'cloud:aerith': { zh: 'Cloud 和 Aerith 有温柔牵引与命运感，但不要写成轻浮恋爱聊天。', en: 'Cloud and Aerith have warmth and fate-like pull, but avoid shallow romantic banter.' },
  'barrett:tifa': { zh: 'Barret 和 Tifa 是并肩作战的伙伴，有信任和共同目标。', en: 'Barret and Tifa are comrades with trust and shared purpose.' },
  'sephiroth:cloud': { zh: 'Sephiroth 对 Cloud 有压迫性与操控感，不像普通朋友。', en: 'Sephiroth is oppressive and manipulative toward Cloud, not a normal friend.' },
};

// Opening is fully generated by Claude each time — no fixed variants

function pairKey(a, b) { return [a, b].sort().join(':'); }
const MAX_STEPS = 9;

function ensureMinCast(present, fallback, min = 3) {
  const allowed = ['player', ...CHARACTER_IDS];
  const result = Array.from(new Set([...(present || []), ...(fallback || [])])).filter(id => allowed.includes(id));
  if (!result.includes('player')) result.unshift('player');
  const pool = ['cloud', 'tifa', 'aerith', 'zack', 'barrett', 'sephiroth'];
  let c = Math.floor(Math.random() * pool.length);
  while (result.length < min && pool.some(id => !result.includes(id))) {
    const id = pool[c % pool.length];
    if (!result.includes(id)) result.push(id);
    c += 1;
  }
  return result;
}

function ensureFreeOption(options, lang) {
  const safe = Array.isArray(options) ? options.filter(Boolean) : [];
  if (safe.some(o => o.target === 'end')) return safe.slice(0, 4);
  const nonFree = safe.filter(o => o.target !== 'free').slice(0, 3);
  const free = safe.find(o => o.target === 'free') || { text: lang === 'zh' ? '直接说出自己的想法或行动' : 'Say exactly what you want to do or say', target: 'free' };
  return [...nonFree, free];
}

function buildCanonGuide(ids, lang) {
  const rows = [];
  const unique = Array.from(new Set(ids.filter(Boolean)));
  for (let i = 0; i < unique.length; i++) {
    for (let j = i + 1; j < unique.length; j++) {
      const k = pairKey(unique[i], unique[j]);
      if (CANON_RELATIONSHIPS[k]) rows.push(CANON_RELATIONSHIPS[k][lang]);
    }
  }
  return rows.length ? rows.map(x => `- ${x}`).join('\n') : (lang === 'zh' ? '- 当前角色之间没有需要额外强调的原作关系。' : '- No extra canon relationship needs emphasis.');
}

function getArcInstruction(step, lang) {
  if (lang === 'zh') {
    if (step <= 2) return '早期剧情：从一个鲜明的起点展开，让至少2名角色参与行动或表态。';
    if (step <= 5) return '中期剧情：引入或强化不同角色的目标冲突，至少3名原作角色在场。';
    if (step <= 8) return '后期剧情：角色立场变得明显，玩家选择必须影响信任、牺牲、真相或队伍分裂。';
    return '高潮剧情：收束前文线索，给出一个有力量、有升华、有代价的结局。';
  }
  if (step <= 2) return 'Early arc: start strong, involve at least two characters.';
  if (step <= 5) return 'Middle arc: conflicting goals, aim for three canon characters.';
  if (step <= 8) return 'Late arc: sharp positions, choices must affect trust or sacrifice.';
  return 'Climax: tie threads together, deliver a meaningful ending.';
}

function pickOpeningCast() {
  // Pick 1-3 random characters (all combinations allowed)
  const pool = [...CHARACTER_IDS].sort(() => Math.random() - 0.5);
  const count = 1 + Math.floor(Math.random() * 3); // 1, 2, or 3
  return ['player', ...pool.slice(0, count)];
}

function buildStoryPrompt({ lang, playerName, openingCast, previousScene, playerText, isOpening, step, knownCast }) {
  const present = isOpening ? openingCast : (previousScene?.present || ['player', 'cloud', 'tifa']);
  const names = present.map(id => id === 'player' ? playerName : CHAR_NAMES[lang][id]).join(', ');
  const speakerChoices = CHARACTER_IDS.filter(id => present.includes(id)).join('|') || 'cloud|tifa';

  const guide = lang === 'zh'
    ? `玩家名：${playerName}\n原作关系：\n${buildCanonGuide(present, lang)}`
    : `Player name: ${playerName}\nCanon relationships:\n${buildCanonGuide(present, lang)}`;

  if (isOpening) {
    const castStr = present.map(id => id === 'player' ? playerName : CHAR_NAMES[lang][id]).join('、');
    const castIds = JSON.stringify(present);
    return lang === 'zh'
      ? `你是互动文字游戏叙事引擎。为本次游戏生成一个全新的开场场景。
本局在场角色（固定，不要更改）：${castStr}
${guide}
规则：
- 自由选择 FF7 世界中的任意地点，不要总是用第七天堂或废墟。
- 设定一个具体的悬念、冲突或意外，让开局立刻有张力。
- present 字段必须严格等于 ${castIds}，不要增删角色。
返回 ONLY 一个严格 JSON object：
{"location":"地点","narration":"旁白2-3句","speaker":"${speakerChoices}","dialogue":"一句台词","present":${castIds},"options":[{"text":"具体选项1","target":"joy_action"},{"text":"具体选项2","target":"joy_action"},{"text":"具体选项3","target":"joy_action"},{"text":"直接说出自己的想法或行动","target":"free"}],"readyForFinale":false,"finaleChoiceText":""}`
      : `You are an interactive narrative engine. Generate a brand-new opening scene for this playthrough.
Fixed cast for this run (do not change): ${names}
${guide}
Rules:
- Choose any FF7 location — avoid always using Seventh Heaven or ruins.
- Create a specific tension, conflict, or surprise so the opening has immediate stakes.
- The present field must exactly equal ${castIds}.
Return ONLY one strict JSON object:
{"location":"place","narration":"2-3 sentences","speaker":"${speakerChoices}","dialogue":"one line","present":${castIds},"options":[{"text":"specific option 1","target":"joy_action"},{"text":"specific option 2","target":"joy_action"},{"text":"specific option 3","target":"joy_action"},{"text":"Say exactly what you want to do or say","target":"free"}],"readyForFinale":false,"finaleChoiceText":""}`;
  }

  // Characters not yet seen — Claude may naturally introduce them if the story allows
  const unseen = knownCast
    ? CHARACTER_IDS.filter(id => !knownCast.includes(id))
    : [];
  const unseenLine = unseen.length
    ? (lang === 'zh'
        ? `\n尚未出场的角色：${unseen.map(id => CHAR_NAMES.zh[id]).join('、')}（如果剧情自然允许，可以让其中一人出现；不强制）`
        : `\nCharacters not yet introduced: ${unseen.map(id => CHAR_NAMES.en[id]).join(', ')} (you may naturally introduce one if the story allows; not required)`)
    : '';

  const presentIds = `[${present.map(id => `"${id}"`).join(',')}]`;

  return lang === 'zh'
    ? `你是互动文字游戏叙事引擎。根据玩家选择推进下一幕。\n当前在场：${names}\n${guide}\n当前阶段：${getArcInstruction(step, lang)}\n玩家选择：${playerText}${unseenLine}\n返回 ONLY 一个严格 JSON object：\n{"location":"地点","narration":"旁白2-3句","speaker":"${speakerChoices}","dialogue":"一句角色台词","present":${presentIds},"options":[{"text":"正面对抗选项","target":"joy_action"},{"text":"保护共情选项","target":"joy_action"},{"text":"调查理性选项","target":"joy_action"},{"text":"直接说出自己的想法或行动","target":"free"}],"readyForFinale":${step >= MAX_STEPS - 1},"finaleChoiceText":${step >= MAX_STEPS - 1 ? '"走向结局"' : '""'}}`
    : `You are an interactive narrative engine. Continue the story.\nCurrent cast: ${names}\n${guide}\nCurrent arc: ${getArcInstruction(step, lang)}\nPlayer choice: ${playerText}${unseenLine}\nReturn ONLY one strict JSON object:\n{"location":"place","narration":"2-3 sentences","speaker":"${speakerChoices}","dialogue":"one line","present":${presentIds},"options":[{"text":"Confrontation option","target":"joy_action"},{"text":"Protection option","target":"joy_action"},{"text":"Investigation option","target":"joy_action"},{"text":"Say exactly what you want to do or say","target":"free"}],"readyForFinale":${step >= MAX_STEPS - 1},"finaleChoiceText":${step >= MAX_STEPS - 1 ? '"Move toward the ending"' : '""'}}`;
}

function buildFinalePrompt({ lang, playerName, scene, history }) {
  const present = scene?.present || ['player', 'cloud'];
  const speakerChoices = present.filter(id => id !== 'player').join('|') || 'cloud';
  const logText = history.slice(-6).map(h => `${h.role}: ${h.content}`).join('\n');

  return lang === 'zh'
    ? `你是互动文字游戏终章引擎。根据故事历史生成结局。\n玩家名：${playerName}\n故事记录（最近几幕）：\n${logText}\n结局旁白要5-8句，有升华，有代价。\n返回 ONLY 一个严格 JSON object：\n{"endingTitle":"结局标题","endingSummary":"3-5句总结","endingTone":"归来","narration":"5-8句结局旁白","speaker":"${speakerChoices}","dialogue":"最后1-2句台词"}`
    : `You are the finale engine. Generate an ending from the story history.\nPlayer name: ${playerName}\nRecent story log:\n${logText}\nNarration should be 5-8 sentences with emotional lift and consequence.\nReturn ONLY one strict JSON object:\n{"endingTitle":"title","endingSummary":"3-5 sentences","endingTone":"return","narration":"5-8 sentence narration","speaker":"${speakerChoices}","dialogue":"final 1-2 line"}`;
}

// ── Component ─────────────────────────────────────────────────────────────────

export function StoryScreen({ lang, playerName, scene, setScene, history, setHistory, storyLog, setStoryLog, endingMeta, setEndingMeta, onOpenChat, onBackToStart, onViewReview }) {
  // phase: idle | loading | narration | narrationPause | dialogue | options | ended
  const [phase, setPhase] = useState(endingMeta ? 'ended' : scene ? 'options' : 'idle');
  // Restore dialogue text immediately when returning from review (no typewriter needed)
  const [displayText, setDisplayText] = useState(scene?.dialogue || '');
  const [speaker, setSpeaker] = useState(scene ? (CHAR_NAMES[lang][scene.speaker] || scene.speaker) : '');
  const [speakerColor, setSpeakerColor] = useState(scene ? (CHAR_COLORS[scene.speaker] || colors.subtext) : colors.subtext);
  const [presentChars, setPresentChars] = useState(scene?.present || []);
  const [activeChar, setActiveChar] = useState(scene?.speaker || null);
  const [options, setOptions] = useState(scene?.options || []);
  const [freeMode, setFreeMode] = useState(false);
  const [freeText, setFreeText] = useState('');
  const [loadingMsg, setLoadingMsg] = useState('');
  const [step, setStep] = useState(0);
  const [pendingScene, setPendingScene] = useState(null);
  const [knownCast, setKnownCast] = useState(scene?.present || []);
  const typeRef = useRef(null);

  function typeText(text, onDone) {
    if (typeRef.current) clearInterval(typeRef.current);
    setDisplayText('');
    let i = 0;
    typeRef.current = setInterval(() => {
      if (i < String(text).length) {
        setDisplayText(String(text).slice(0, ++i));
      } else {
        clearInterval(typeRef.current);
        if (onDone) onDone();
      }
    }, 22);
  }

  useEffect(() => () => { if (typeRef.current) clearInterval(typeRef.current); }, []);

  function appendLog(entry) {
    setStoryLog(prev => [...prev, { id: `${Date.now()}-${Math.random().toString(16).slice(2)}`, step, time: new Date().toISOString(), ...entry }]);
  }

  function normalizeScene(parsed, fallbackPresent) {
    const allowed = ['player', ...CHARACTER_IDS];
    let present = Array.from(new Set((parsed.present || fallbackPresent).filter(id => allowed.includes(id))));
    if (!present.includes('player')) present.unshift('player');
    present = ensureMinCast(present, fallbackPresent, step >= 3 ? 4 : 3);
    const speakerId = allowed.includes(parsed.speaker) ? parsed.speaker : (present.find(id => id !== 'player') || 'cloud');
    return {
      location: parsed.location || (lang === 'zh' ? '未知地点' : 'Unknown Place'),
      narration: parsed.narration || '',
      speaker: speakerId,
      dialogue: parsed.dialogue || '',
      present,
      options: ensureFreeOption(parsed.options, lang),
      readyForFinale: Boolean(parsed.readyForFinale),
      finaleChoiceText: parsed.finaleChoiceText || '',
    };
  }

  function startNarration(sc, playerChoice) {
    setPresentChars(sc.present);
    setActiveChar(null);
    setSpeaker(lang === 'zh' ? '旁白' : 'Narrator');
    setSpeakerColor(colors.subtext);
    setPhase('narration');
    typeText(sc.narration, () => {
      setPendingScene({ ...sc, playerChoice });
      setPhase('narrationPause');
    });
  }

  function continueToDialogue() {
    const sc = pendingScene;
    if (!sc) return;
    setPhase('dialogue');
    setSpeaker(sc.speaker === 'player' ? playerName : CHAR_NAMES[lang][sc.speaker] || sc.speaker);
    setSpeakerColor(CHAR_COLORS[sc.speaker] || colors.subtext);
    setActiveChar(sc.speaker);
    typeText(sc.dialogue, () => {
      appendLog({ type: 'scene', location: sc.location, playerChoice: sc.playerChoice || '', narration: sc.narration, speaker: sc.speaker, dialogue: sc.dialogue, present: sc.present });
      const newHistory = [...history, { role: 'user', content: `Scene: ${sc.narration}` }, { role: 'assistant', content: `[${sc.speaker}]: ${sc.dialogue}` }];
      setHistory(newHistory);

      if (step >= MAX_STEPS || sc.readyForFinale) {
        setOptions([{ text: sc.finaleChoiceText || (lang === 'zh' ? '走向结局' : 'Move toward the ending'), target: 'end' }]);
      } else {
        setOptions(sc.options);
      }
      setFreeMode(false);
      setPhase('options');
      setPendingScene(null);
    });
  }

  async function startStory() {
    const openingCast = pickOpeningCast();
    setPhase('loading');
    setLoadingMsg(lang === 'zh' ? '连接生命之流…' : 'Connecting to the Lifestream…');
    setStep(0);
    setScene(null);
    setHistory([]);
    setStoryLog([]);
    setEndingMeta(null);
    setKnownCast(openingCast);

    try {
      const prompt = buildStoryPrompt({ lang, playerName, openingCast, isOpening: true, step: 0 });
      const raw = await callChatAPI(prompt, [{ role: 'user', content: lang === 'zh' ? '生成开场' : 'Generate opening' }]);
      let parsed;
      try { parsed = safeJsonObject(raw); } catch { parsed = { location: lang === 'zh' ? '生命之流裂隙' : 'Lifestream Rift', narration: raw.slice(0, 300), speaker: openingCast[1], dialogue: lang === 'zh' ? '先别急，我们把情况理清楚。' : 'Hold on. Let us make sense of this.', present: openingCast, options: [] }; }
      const sc = normalizeScene(parsed, openingCast);
      setScene(sc);
      startNarration(sc, '');
    } catch (err) {
      setPhase('idle');
    }
  }

  async function advanceStory(playerText, isFree) {
    const nextStep = step + 1;

    setPhase('loading');
    setLoadingMsg(lang === 'zh' ? '生命之流涌动…' : 'The Lifestream stirs…');
    setOptions([]);
    setFreeMode(false);
    setFreeText('');

    try {
      const prompt = buildStoryPrompt({ lang, playerName, previousScene: scene, playerText, isOpening: false, step: nextStep, knownCast });
      const raw = await callChatAPI(prompt, [...history.slice(-8), { role: 'user', content: playerText }]);
      let parsed;
      try { parsed = safeJsonObject(raw); } catch { parsed = null; }
      if (!parsed) {
        setPhase('options');
        setOptions(ensureFreeOption(scene?.options || [], lang));
        return;
      }
      const sc = normalizeScene(parsed, scene?.present || ['player', 'cloud', 'tifa']);
      // Update knownCast with whoever Claude put in this scene
      setKnownCast(prev => Array.from(new Set([...prev, ...sc.present])));
      setScene(sc);
      setStep(nextStep);
      startNarration(sc, playerText);
    } catch (err) {
      setPhase('options');
      setOptions(ensureFreeOption(scene?.options || [], lang));
    }
  }

  async function doFinale() {
    setPhase('loading');
    setLoadingMsg(lang === 'zh' ? '终章生成中…' : 'Generating finale…');
    setOptions([]);

    try {
      const prompt = buildFinalePrompt({ lang, playerName, scene, history });
      const raw = await callChatAPI(prompt, [...history.slice(-8), { role: 'user', content: lang === 'zh' ? '生成终章' : 'Generate finale' }]);
      let finale;
      try { finale = safeJsonObject(raw); } catch { finale = { endingTitle: lang === 'zh' ? '生命之流的回声' : 'Echo of the Lifestream', endingSummary: lang === 'zh' ? '旅程结束了，但你的选择留下了痕迹。' : 'The journey ends, but your choices leave a trace.', endingTone: 'return', narration: lang === 'zh' ? '生命之流短暂失去了声音，但旅程并没有因此消失。' : 'The Lifestream loses its voice briefly, but the journey does not vanish.', speaker: 'cloud', dialogue: lang === 'zh' ? '如果这就是终点，那至少是我们自己走到的地方。' : 'If this is the end, at least we reached it by our own choices.' }; }

      appendLog({ type: 'finale', location: scene?.location || '', narration: finale.narration, speaker: finale.speaker, dialogue: finale.dialogue, present: scene?.present || [] });
      setEndingMeta({ endingTitle: finale.endingTitle, endingSummary: finale.endingSummary, endingTone: finale.endingTone, finalCast: scene?.present || [] });

      setSpeaker(lang === 'zh' ? '旁白' : 'Narrator');
      setSpeakerColor(colors.subtext);
      setActiveChar(null);
      setPhase('narration');
      typeText(finale.narration, () => {
        setPendingScene({ speaker: finale.speaker, dialogue: finale.dialogue, options: [], isFinale: true });
        setPhase('narrationPause');
      });
    } catch {
      setPhase('ended');
    }
  }

  function handleOption(opt) {
    if (opt.target === 'free') { setFreeMode(true); setOptions([]); return; }
    if (opt.target === 'end') { doFinale(); return; }
    advanceStory(opt.text, false);
  }

  function handleNarrationContinue() {
    if (pendingScene?.isFinale) {
      setPhase('dialogue');
      setSpeaker(pendingScene.speaker === 'player' ? playerName : CHAR_NAMES[lang][pendingScene.speaker] || pendingScene.speaker);
      setSpeakerColor(CHAR_COLORS[pendingScene.speaker] || colors.subtext);
      setActiveChar(pendingScene.speaker);
      typeText(pendingScene.dialogue, () => {
        setPendingScene(null);
        setPhase('ended');
      });
    } else {
      continueToDialogue();
    }
  }

  // ── Render ────────────────────────────────────────────────────────────────

  if (phase === 'idle') {
    return (
      <View style={styles.center}>
        <FFPanel style={styles.idlePanel}>
          <Text style={styles.kicker}>FINAL FANTASY VII</Text>
          <Text style={styles.bigTitle}>TEXT CHRONICLE</Text>
          <Text style={styles.subtitle}>{lang === 'zh' ? '主线叙事 · 最多9幕 · AI驱动' : 'Main narrative · Up to 9 scenes · AI-driven'}</Text>
          <FFButton variant="primary" onPress={startStory}>{lang === 'zh' ? '开始故事' : 'Start Story'}</FFButton>
          <FFButton onPress={onOpenChat}>💬 {lang === 'zh' ? '群聊' : 'Group Chat'}</FFButton>
        </FFPanel>
      </View>
    );
  }

  return (
    <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.wrap}>
      {/* Top bar */}
      <View style={styles.topRow}>
        <FFButton onPress={onBackToStart}>{lang === 'zh' ? '返回' : 'Back'}</FFButton>
        {scene?.location ? <Text style={styles.location} numberOfLines={1}>{scene.location}</Text> : null}
        <FFButton variant="primary" onPress={onOpenChat}>💬 {lang === 'zh' ? '群聊' : 'Chat'}</FFButton>
      </View>

      {/* Avatar rail */}
      {presentChars.length > 0 && (
        <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.avatarRail} contentContainerStyle={styles.avatarContent}>
          {presentChars.map(id => (
            <CharacterAvatar key={id} id={id} lang={lang} playerName={playerName} active={id === activeChar} />
          ))}
        </ScrollView>
      )}

      {/* Text panel */}
      <FFPanel style={styles.textPanel}>
        <Text style={[styles.speakerLabel, { color: speakerColor }]}>{speaker}</Text>
        <ScrollView style={styles.textScroll}>
          <Text style={[styles.displayText, (phase === 'narration' || phase === 'narrationPause') && styles.narrationText]}>
            {displayText}
            {(phase === 'narration' || phase === 'dialogue') ? <Text style={styles.cursor}>▌</Text> : null}
          </Text>
        </ScrollView>

        {/* Continue button */}
        {(phase === 'narrationPause') && (
          <TouchableOpacity style={styles.continueBtn} onPress={handleNarrationContinue}>
            <Text style={styles.continueBtnText}>{lang === 'zh' ? '▸ 继续' : '▸ continue'}</Text>
          </TouchableOpacity>
        )}
      </FFPanel>

      {/* Options / free input */}
      {phase === 'options' && (
        <FFPanel style={styles.optionsPanel}>
          <Text style={styles.chooseLabel}>{lang === 'zh' ? '— 选择行动 —' : '— choose your action —'}</Text>
          {freeMode ? (
            <View style={styles.freeBox}>
              <TextInput
                value={freeText}
                onChangeText={setFreeText}
                placeholder={lang === 'zh' ? '以你的身份说话…' : 'Speak as yourself…'}
                placeholderTextColor="rgba(203,222,247,0.4)"
                style={styles.freeInput}
                multiline
                autoFocus
              />
              <View style={styles.freeRow}>
                <FFButton onPress={() => { setFreeMode(false); setOptions(scene?.options || []); }}>{lang === 'zh' ? '返回' : 'Back'}</FFButton>
                <FFButton variant="primary" disabled={!freeText.trim()} onPress={() => advanceStory(freeText.trim(), true)}>
                  {lang === 'zh' ? '发送' : 'Send'}
                </FFButton>
              </View>
            </View>
          ) : (
            <View style={styles.optionList}>
              {options.map((opt, idx) => (
                <Pressable key={`${opt.text}-${idx}`} style={({ pressed }) => [styles.optionBtn, pressed && styles.optionBtnPressed]} onPress={() => handleOption(opt)}>
                  <Text style={styles.optionText}>▸ {opt.text}</Text>
                </Pressable>
              ))}
            </View>
          )}
        </FFPanel>
      )}

      {/* Ended */}
      {phase === 'ended' && endingMeta && (
        <FFPanel style={styles.endedPanel}>
          <Text style={styles.endingTitle}>{endingMeta.endingTitle}</Text>
          <Text style={styles.endingSummary}>{endingMeta.endingSummary}</Text>
          <View style={styles.endBtns}>
            <FFButton onPress={() => onViewReview(storyLog, endingMeta, lang)}>{lang === 'zh' ? '回顾故事' : 'View Review'}</FFButton>
            <FFButton variant="primary" onPress={startStory}>{lang === 'zh' ? '重开故事' : 'New Story'}</FFButton>
          </View>
        </FFPanel>
      )}

      <LifestreamLoader visible={phase === 'loading'} lang={lang} />
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  wrap: { flex: 1, padding: 14, gap: 10 },
  center: { flex: 1, justifyContent: 'center', padding: 18 },
  idlePanel: { padding: 24, gap: 16 },
  kicker: { color: colors.cyan, fontSize: 11, letterSpacing: 2.5 },
  bigTitle: { color: colors.text, fontSize: 28, fontWeight: '800', letterSpacing: 1.4 },
  subtitle: { color: colors.subtext, lineHeight: 22 },
  topRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  location: { color: colors.cyan, fontSize: 12, fontWeight: '700', flex: 1, textAlign: 'center' },
  avatarRail: { maxHeight: 86 },
  avatarContent: { gap: 12, paddingVertical: 4 },
  textPanel: { flex: 1, padding: 18, gap: 10 },
  speakerLabel: { fontSize: 11, letterSpacing: 1.4, fontWeight: '700' },
  textScroll: { flex: 1 },
  displayText: { color: colors.text, fontSize: 16, lineHeight: 26 },
  narrationText: { color: '#c8e0ff', fontStyle: 'italic', lineHeight: 28 },
  cursor: { color: colors.cyan, opacity: 0.8 },
  continueBtn: { alignSelf: 'flex-end', paddingVertical: 8, paddingHorizontal: 16 },
  continueBtnText: { color: colors.cyan, fontSize: 13, letterSpacing: 1 },
  optionsPanel: { padding: 14, gap: 8, maxHeight: 300 },
  chooseLabel: { color: colors.subtext, fontSize: 11, letterSpacing: 1.2, textAlign: 'center', marginBottom: 4 },
  optionList: { gap: 8 },
  optionBtn: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 13, backgroundColor: 'rgba(255,255,255,0.04)' },
  optionBtnPressed: { backgroundColor: 'rgba(99,156,255,0.15)', transform: [{ translateY: 1 }] },
  optionText: { color: colors.text, fontSize: 14, lineHeight: 20 },
  freeBox: { gap: 10 },
  freeRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  freeInput: { minHeight: 90, color: colors.text, borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.panel2, padding: 13, textAlignVertical: 'top', fontSize: 15, lineHeight: 22 },
  endedPanel: { padding: 18, gap: 12 },
  endingTitle: { color: colors.cyan, fontSize: 16, fontWeight: '800', letterSpacing: 0.8 },
  endingSummary: { color: colors.text, lineHeight: 24 },
  endBtns: { flexDirection: 'row', gap: 10 },
});
